version: '3'
services:
    portainer:
      image: portainer/portainer
      ports:
        - "9000:9000"
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer:/data
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    filebeat:
      image: docker.elastic.co/beats/filebeat:6.5.4
      user: root
      depends_on:
        - elasticsearch
        - logstash
        - kibana
      volumes:
        - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      environment:
        - output.elasticsearch.hosts=["elasticsearch:9200"]
        - strict.perms=false
    logstash:
      build:
        context: ./logstash
        dockerfile: Dockerfile
      image: logstash:latest
      ports:
        - "5044:5044"
        - "9600:9600"
      depends_on:
        - elasticsearch
        - kibana
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    kibana:
      image: docker.elastic.co/kibana/kibana-oss:6.7.1
      depends_on:
        - elasticsearch
      ports:
        - '5601:5601'
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        - /var/run/docker.sock:/var/run/docker.sock
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /var/run/docker.sock:/var/run/docker.sock
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    plotter:
      image: plotter:latest
      depends_on:
        - elasticsearch
        - logstash
        - kibana
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
